// ⚠️ PLACEHOLDER — REGENERATE BEFORE RUNNING AGAINST A REAL PROJECT.
//
// This file is normally generated by the FlutterFire CLI. The values below are
// dummy placeholders so the project compiles; the app will NOT connect to
// Firebase until you regenerate it:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// (See refactor_guide/DevOps.md.) `flutterfire configure` overwrites this file
// with your project's real options for every configured platform.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform — '
          'run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'myroom-app',
    authDomain: 'myroom-app.firebaseapp.com',
    storageBucket: 'myroom-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'myroom-app',
    storageBucket: 'myroom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'myroom-app',
    storageBucket: 'myroom-app.appspot.com',
    iosBundleId: 'com.example.myroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'myroom-app',
    storageBucket: 'myroom-app.appspot.com',
    iosBundleId: 'com.example.myroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'myroom-app',
    authDomain: 'myroom-app.firebaseapp.com',
    storageBucket: 'myroom-app.appspot.com',
  );
}
